extensions = ['sphinxcontrib.bibtex','sphinx.ext.mathjax']
master_doc = 'index'
project = u'Blockchain projects'
copyright = u'Public'
author = u'-'
show_authors = True
html_theme = "classic"
bgcolor = "#F0FFFF"
full_logo = True
html_logo = 'images/logo.png'
html_show_copyright = False
html_show_sphinx = False
